<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>HotelPOS.Printing</RootNamespace>
    <UseWindowsForms>true</UseWindowsForms>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="QuestPDF" Version="2024.7.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\HotelPOS.Common\HotelPOS.Common.csproj" />
    <ProjectReference Include="..\HotelPOS.Logging\HotelPOS.Logging.csproj" />
  </ItemGroup>

</Project>
